### ISSUE TITLE
Image Resizing

### ISSUE THREAD

**Issue by HannahDelaney** [HannahDelaney/but-em-buttons#1]
Hi @charlie-quinn,

I am having trouble resizing the images. I've exported and compressed both the photoshop and illustrator files (several times actually!) and they still seem to be too large. I was following the earlier lessons for this, so I'm not sure what is wrong.

Everything else is satisfying markbot, it's just the images that are left.

Thanks!
Hannah

**Comment by charlie-quinn** [comment]
## Photoshop
- [ ] open the `Save for web` window (command + alt + shift + s)
- [ ] try these export settings:
  - [ ] File format: JPEG
  - [ ] Quality: 20%
  - [ ] Blur: 0.2 (I would say it's adjustable up to 1)
  - [ ] Image size: 800x800px
## Illustrator
- [ ] resize artwork in AI to be 100px in height
  - this asset is pretty small on our site, so we don't need it to be any larger than this
- [ ] smush it using `spritebot` and/or [svgomg](https://jakearchibald.github.io/svgomg/)
Markbot should be much happier 🤖🎉

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by HannahDelaney** [comment]
Thanks!
